labgrid-aparcar-openwrt_one:
  NetworkService:
    address: 192.168.1.1%vlan113
    username: root
  PDUDaemonPort:
    host: localhost:16421
    index: 1
    pdu: 192.168.128.2
  TFTPProvider:
    external: openwrt_one/
    internal: /srv/tftp/openwrt_one/
  USBSerialPort:
    match:
      ID_PATH: platform-xhci-hcd.0-usb-0:1.1.1:1.0

labgrid-aparcar-bananapi_bpi-r4-lite:
  NetworkService:
    address: 192.168.1.1%vlan114
    username: root
  PDUDaemonPort:
    host: localhost:16421
    index: 2
    pdu: 192.168.128.2
  TFTPProvider:
    external: bananapi_bpi-r4-lite/
    internal: /srv/tftp/bananapi_bpi-r4-lite/
  USBSerialPort:
    match:
      ID_PATH: platform-xhci-hcd.0-usb-0:1.1.2:1.0
